### ISSUE TITLE
Make it possible to display read lengths in the HTML output of proteins-to-pathogens.py

### ISSUE THREAD

**Issue by terrycojones** [acorg/dark-matter#537]
Sofia wants this. Should be off by default (as many reads can match a protein and it doesn't seem generally useful to dump out hundreds or thousands of read lengths).

**Comment by bamueh** [comment]
You could count the read lengths and output a `length: count` or something. But that would only make the output smaller if many of the reads have the same length.

**Comment by terrycojones** [comment]
Yes, could do that too. Sofia almost always has just one read (a contig in her case) matching each subject, and wants to know its length. So I'll just print them all and see how she gets on with that. Thanks :-)
